# Generated by Django 3.1.3 on 2022-03-01 01:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_results'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Results',
        ),
        migrations.AlterModelOptions(
            name='result',
            options={},
        ),
    ]
