# Generated by Django 3.1.3 on 2022-03-01 01:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_auto_20220301_0134'),
    ]

    operations = [
        migrations.CreateModel(
            name='Results',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recepts_num', models.IntegerField(db_column='recept_num')),
                ('judge', models.IntegerField(db_column='judge')),
                ('time', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AlterModelOptions(
            name='result',
            options={'managed': False},
        ),
    ]
