# Generated by Django 3.1.3 on 2022-02-28 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('image', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='picpost',
            name='plate_num',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
