# Generated by Django 3.1.3 on 2022-02-28 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('image', '0002_picpost_plate_num'),
    ]

    operations = [
        migrations.AlterField(
            model_name='picpost',
            name='model_pic',
            field=models.ImageField(max_length=1000, upload_to='image/%Y/%m/%d'),
        ),
    ]
